name: Generate Contributions
on:
  push:
    branches:
      - main
      
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git Config
        run: |
          git config --global user.email "careers@thebeelogix.com"
          git config --global user.name "CipherQuest"

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Fetch Latest Change
        run: |
          git fetch origin main

      - name: Select Random Folder and File, and Make Changes
        run: |
          git pull --rebase origin main
          random_folder=$(find src/pages -type d | shuf -n 1) # Select a random folder
          random_file=$(find "$random_folder" -type f | shuf -n 1) # Select a random file within the folder
          
          echo "Making change to $random_file in folder $random_folder"
          echo "# Contribution: Added comment" >> "$random_file"
          
          git add "$random_file"
          git commit -m "Add comments to $random_file in folder $random_folder"          
          git push
          
